name: Release

on:
  push:
    tags:
      - 'v*'
      - '*dev*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Setup Credentials
        uses: KasukuSakura/maven-center-publish@main
        with:
          credential: ${{ secrets.MVN_CENTERAL_CREDENTIAL }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true

      - name: Build Project
        run: gradle build --info --full-stacktrace

      - name: Publish Modules
        run: gradle publish --info
